[build]
builder = "nixpacks"
buildCommand = "echo building!"

[deploy]
preDeployCommand = ["pip install -r requirements.txt","adk web"]
startCommand = "echo starting!"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "never"

--

