[build]
builder = "NIXPACKS"
nixpacksPlan = {"providers":["...","python"]}
watchPatterns = ["/google-adk"]

[deploy]
runtime = "V2"
numReplicas = 1
startCommand = "adk web"
preDeployCommand = ["pip install -r requirments.txt"]
sleepApplication = false
multiRegionConfig = {"europe-west4-drams3a":{"numReplicas":1}}
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10